name: CMake-Debug

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test Individual
      working-directory: ${{github.workspace}}/build
      run: make test mars-test

    - name: Test End to End
      working-directory: ${{github.workspace}}/build
      run: make test mars-e2e-test
